/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/build/build-ux-ssot.ts
 * Source: governance/ux/*.yaml
 */

export const SSOT_HASHES = {
    "roleModel": "f32171e6bedd14fe74215e98d94b4b7af2aab8ef0a67bd13664b126cedb76b9f",
    "roleJourneys": "b19e2d235d467413fd5222019486a3d612a4c0f862c8164b7f51830d80bbb7df",
    "caseShelves": "55928c18fc227a4217ea8c1e8fa0f4d8097d71c7c26c1ae7217f1e9a98924c42",
    "tripodMap": "6e7667b71ce41d840661683f9cdbc933345ecc4eb9c35171bf810c13c5c1238d",
    "componentRegistry": "016e06b1482c88ae24b4da60f80f77a3001ae03e80e9fb4da8d82ce43d9c21c9",
    "pageBindings": "8e1a90e3e58af3c8e3b7df7fb597538b55770f76ec2fd9cccdcaa08daba8b111"
};

export const ROLES = [
    {
        "id": "architect",
        "title": "Enterprise Architect",
        "intent": "Verify Interoperability & Standards",
        "primary_questions": [
            "Can I chain LangGraph with MCP?",
            "Is the execution deterministic?",
            "What is the evidence structure?"
        ],
        "must_see_cases": {
            "pass_precedent": "interop-mcp-a2a-langgraph-d1-real-runner-det-001",
            "fail_precedent": "mcp-d1-fail-benchmark-001",
            "shim_notice_case": "metagpt-d1-real-runner-det-001"
        },
        "must_see_proof_targets": [
            "mplp://timeline/event/3"
        ],
        "must_show_blocks": [
            "BLOCK_INTEROP_VISUALIZER",
            "BLOCK_VERDICT_BADGE"
        ],
        "required_disclaimer_tokens": [
            "DISCL_NOT_CERTIFICATION",
            "DISCL_READING_AID_ONLY"
        ]
    },
    {
        "id": "compliance",
        "title": "Compliance Officer",
        "intent": "Assess Regulatory Mapping",
        "primary_questions": [
            "How does this map to EU AI Act?",
            "Where is the provenance seal?",
            "Is this a certification?"
        ],
        "must_see_cases": {
            "pass_precedent": "interop-mcp-a2a-langgraph-d1-real-runner-det-001",
            "fail_precedent": "mcp-d1-fail-benchmark-001",
            "shim_notice_case": "metagpt-d1-real-runner-det-001"
        },
        "must_see_proof_targets": [
            "mplp://artifacts/verdict.json"
        ],
        "must_show_blocks": [
            "BLOCK_REG_MAPPING_MATRIX",
            "BLOCK_DISCLAIMER_BANNER"
        ],
        "required_disclaimer_tokens": [
            "DISCL_NOT_COMPLIANCE",
            "DISCL_READING_AID_ONLY"
        ]
    },
    {
        "id": "auditor",
        "title": "Third-Party Auditor",
        "intent": "Verify Dispute & Root Cause",
        "primary_questions": [
            "Where is the failure root cause?",
            "Is the seal broken?",
            "Can I replay this run?"
        ],
        "must_see_cases": {
            "pass_precedent": "interop-mcp-a2a-langgraph-d1-real-runner-det-001",
            "fail_precedent": "mcp-d1-fail-benchmark-001",
            "shim_notice_case": "metagpt-d1-real-runner-det-001"
        },
        "must_see_proof_targets": [
            "mplp://artifacts/verdict.json"
        ],
        "must_show_blocks": [
            "BLOCK_DISPUTE_PANEL",
            "BLOCK_EVIDENCE_DOCKET"
        ],
        "required_disclaimer_tokens": [
            "DISCL_NO_ENDORSEMENT"
        ]
    },
    {
        "id": "builder",
        "title": "Framework Developer",
        "intent": "Implement Evidence Protocol",
        "primary_questions": [
            "What is the manifest schema?",
            "How do I emit A2A envelopes?",
            "Where is the LangGraph example?"
        ],
        "must_see_cases": {
            "pass_precedent": "interop-mcp-a2a-langgraph-d1-real-runner-det-001",
            "fail_precedent": "mcp-d1-fail-benchmark-001",
            "shim_notice_case": "metagpt-d1-real-runner-det-001"
        },
        "must_see_proof_targets": [
            "mplp://artifacts/manifest.json"
        ],
        "must_show_blocks": [
            "BLOCK_MANIFEST_VIEWER"
        ],
        "required_disclaimer_tokens": [
            "DISCL_NOT_SDK"
        ]
    }
];

export const JOURNEYS = [
    {
        "role": "architect",
        "steps": [
            {
                "route": "/start",
                "expect_blocks": [
                    "BLOCK_ROLE_GATEWAY"
                ],
                "expect_ctas": [
                    "CTA_START_JOURNEY"
                ]
            },
            {
                "route": "/cases/interop-mcp-a2a-langgraph-d1-real-runner-det-001",
                "expect_blocks": [
                    "BLOCK_INTEROP_VISUALIZER",
                    "BLOCK_VERDICT_BADGE"
                ],
                "expect_ctas": [
                    "CTA_VIEW_EVIDENCE"
                ],
                "expect_proof_ptrs": [
                    "mplp://timeline/event/3"
                ]
            }
        ]
    },
    {
        "role": "auditor",
        "steps": [
            {
                "route": "/start",
                "expect_blocks": [
                    "BLOCK_ROLE_GATEWAY"
                ],
                "expect_ctas": [
                    "CTA_INSPECT_FAILURE"
                ]
            },
            {
                "route": "/cases/mcp-d1-fail-benchmark-001",
                "expect_blocks": [
                    "BLOCK_DISPUTE_PANEL",
                    "BLOCK_VERDICT_BADGE"
                ],
                "expect_ctas": [
                    "CTA_VIEW_ROOT_CAUSE"
                ],
                "expect_proof_ptrs": [
                    "mplp://artifacts/verdict.json"
                ]
            }
        ]
    },
    {
        "role": "compliance",
        "steps": [
            {
                "route": "/start",
                "expect_blocks": [
                    "BLOCK_ROLE_GATEWAY"
                ],
                "expect_ctas": [
                    "CTA_VIEW_MAPPING"
                ]
            },
            {
                "route": "/policies/reg-mapping",
                "expect_blocks": [
                    "BLOCK_REG_MAPPING_MATRIX",
                    "BLOCK_DISCLAIMER_BANNER"
                ],
                "expect_ctas": [
                    "CTA_VIEW_EXAMPLE_CASE"
                ]
            }
        ]
    },
    {
        "role": "builder",
        "steps": [
            {
                "route": "/start",
                "expect_blocks": [
                    "BLOCK_ROLE_GATEWAY"
                ],
                "expect_ctas": [
                    "CTA_BUILD_EVIDENCE"
                ]
            },
            {
                "route": "/cases/interop-mcp-a2a-langgraph-d1-real-runner-det-001",
                "expect_blocks": [
                    "BLOCK_MANIFEST_VIEWER"
                ],
                "expect_ctas": [
                    "CTA_DOWNLOAD_ARTIFACTS"
                ]
            }
        ]
    }
];

export const SHELVES = [
    {
        "id": "precedents",
        "title": "Latest Precedents",
        "criteria": "Recent REAL runs with PASS verdict demonstrating key capabilities.",
        "pinned_cases": [
            {
                "id": "interop-mcp-a2a-langgraph-d1-real-runner-det-001",
                "why_this_matters": "First Verified Interop: LangGraph + MCP + A2A."
            },
            {
                "id": "langchain-d1-real-runner-det-001",
                "why_this_matters": "Standard LangChain Reference Implementation."
            }
        ]
    },
    {
        "id": "failures",
        "title": "Dispute Benchmarks",
        "criteria": "Runs specifically designed to fail boundaries for auditor testing.",
        "pinned_cases": [
            {
                "id": "mcp-d1-fail-benchmark-001",
                "why_this_matters": "Benchmark for Root Cause Pointer resolution."
            }
        ]
    },
    {
        "id": "shims",
        "title": "Shimmed Environments",
        "criteria": "Real runs executed in Node Shims pending native container support.",
        "pinned_cases": [
            {
                "id": "metagpt-d1-real-runner-det-001",
                "why_this_matters": "MetaGPT executing in Node20 Shim (Transparency Disclosure)."
            },
            {
                "id": "semantickernel-d1-real-runner-det-001",
                "why_this_matters": "Semantic Kernel executing in Node20 Shim (Transparency Disclosure)."
            }
        ]
    }
];

export const TRIPOD = {
    "inbound": [
        {
            "id": "reg_mapping_access",
            "source": "website:/governance",
            "target_route": "/policies/reg-mapping",
            "required_blocks": [
                "BLOCK_DISCLAIMER_BANNER"
            ]
        },
        {
            "id": "case_deep_link",
            "source": "files:/case-studies",
            "target_route": "/cases/[id]",
            "required_blocks": [
                "BLOCK_VERDICT_BADGE"
            ]
        }
    ],
    "outbound": [
        {
            "id": "clause_definition_link",
            "description": "Link to Clause Definition in Docs",
            "target_pattern": "docs:/laws/{ruleset}/{clause}",
            "required_token": "DISCL_READING_AID_ONLY"
        },
        {
            "id": "evidence_source_link",
            "description": "Link to original evidence source",
            "target_pattern": "external:*",
            "required_token": "DISCL_NOT_LEGAL_ADVICE"
        }
    ]
};

export const COMPONENTS = {
    "blocks": [
        {
            "block_id": "BLOCK_INTEROP_VISUALIZER",
            "component": "InteropGraph",
            "data_binding": "projection.interop_stack",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_STACK_FLOW",
                "LIT_NOT_APPLICABLE"
            ]
        },
        {
            "block_id": "BLOCK_VERDICT_BADGE",
            "component": "VerdictBadge",
            "data_binding": "projection.evaluation.verdict",
            "hardcoded_text_policy": "allowlist",
            "allowed_literals": [
                "PASS",
                "FAIL",
                "REJECTED"
            ]
        },
        {
            "block_id": "BLOCK_DISPUTE_PANEL",
            "component": "DisputePanel",
            "data_binding": "projection.dispute_closure",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_ROOT_CAUSE",
                "LIT_REPLAY_INSTRUCTIONS",
                "LIT_NOT_APPLICABLE",
                "LIT_DISPUTE_CLOSURE"
            ]
        },
        {
            "block_id": "BLOCK_PROVENANCE",
            "component": "ProvenanceCard",
            "data_binding": "projection.provenance",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_NO_ENDORSEMENT"
            ]
        },
        {
            "block_id": "BLOCK_EVIDENCE_DOCKET",
            "component": "EvidenceList",
            "data_binding": "projection.evidence.slices",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_EVIDENCE_DOCKET"
            ]
        },
        {
            "block_id": "BLOCK_ROLE_GATEWAY",
            "component": "RoleSelector",
            "data_binding": "ssot.roles",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_CHOOSE_ROLE",
                "LIT_START_JOURNEY",
                "LIT_NOT_APPLICABLE",
                "DISCL_NOT_CERTIFICATION"
            ]
        },
        {
            "block_id": "BLOCK_HERO",
            "component": "HeroBlock",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_LAWS_TITLE",
                "LIT_LAWS_DESC",
                "LIT_RULESET_VERSION_LABEL",
                "LIT_NOT_APPLICABLE"
            ]
        },
        {
            "block_id": "BLOCK_START_HERO",
            "component": "StartHero",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_START_JOURNEY",
                "LIT_CTA_START_BY_ROLE_DESC"
            ]
        },
        {
            "block_id": "BLOCK_CLAUSE_BROWSER",
            "component": "ClauseList",
            "data_binding": "ruleset.clauses",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "DISCL_READING_AID_ONLY",
                "LIT_CLAUSE_ID",
                "LIT_CLAUSE_NAME",
                "LIT_INTENT",
                "LIT_SURFACES",
                "LIT_PRECEDENTS",
                "LIT_NO_CLAUSES"
            ]
        },
        {
            "block_id": "BLOCK_REG_MAPPING_MATRIX",
            "component": "RegMappingGrid",
            "data_binding": "ruleset.mappings",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "DISCL_READING_AID_ONLY",
                "DISCL_NOT_COMPLIANCE",
                "LIT_ARTICLE",
                "LIT_REQUIREMENT",
                "LIT_MPLP_CLAUSE",
                "LIT_NO_MAPPINGS"
            ]
        },
        {
            "block_id": "BLOCK_MANIFEST_VIEWER",
            "component": "ManifestViewer",
            "data_binding": "projection.manifest",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "DISCL_NOT_SDK",
                "LIT_RUN_ID",
                "LIT_RULESET_VERSION",
                "LIT_SCHEMA_BUNDLE",
                "LIT_PACK_ROOT_HASH",
                "LIT_ENV_REF",
                "LIT_PRODUCED_AT"
            ]
        },
        {
            "block_id": "BLOCK_DISCLAIMER_BANNER",
            "component": "DisclaimerBanner",
            "data_binding": "ssot.tokens",
            "hardcoded_text_policy": "strict_ssot"
        },
        {
            "block_id": "BLOCK_HOME_HERO",
            "component": "HomeHero",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_HOME_TITLE",
                "LIT_HOME_SUBTITLE",
                "LIT_HOME_TAGLINE_NONCERT",
                "LIT_NAV_START",
                "LIT_NAV_CASES"
            ]
        },
        {
            "block_id": "BLOCK_HOME_PRIMARY_CTAS",
            "component": "HomePrimaryCtas",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_CTA_CURATED_RUNS_TITLE",
                "LIT_CTA_CURATED_RUNS_DESC",
                "LIT_CTA_START_BY_ROLE_TITLE",
                "LIT_CTA_START_BY_ROLE_DESC",
                "LIT_CTA_LOCAL_REPRO_TITLE",
                "LIT_CTA_LOCAL_REPRO_DESC"
            ]
        },
        {
            "block_id": "BLOCK_HOME_STATS_ROW",
            "component": "HomeStatsRow",
            "data_binding": "ssot.stats",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_STATS_RUNS",
                "LIT_STATS_RULESET",
                "LIT_STATS_DETERMINISM",
                "LIT_STATS_EVIDENCE_PACKS",
                "LIT_NOT_AVAILABLE"
            ]
        },
        {
            "block_id": "BLOCK_HOME_AUDIT_BANNER",
            "component": "HomeAuditBanner",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_AUDIT_BANNER_LINE1",
                "LIT_AUDIT_BANNER_LINE2",
                "LIT_AUDIT_BANNER_LINE3"
            ]
        },
        {
            "block_id": "BLOCK_HOME_QUICK_START",
            "component": "HomeQuickStart",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_QUICKSTART_TITLE",
                "LIT_QUICKSTART_STEP1",
                "LIT_QUICKSTART_STEP2",
                "LIT_QUICKSTART_STEP3"
            ]
        },
        {
            "block_id": "BLOCK_HOME_RESOURCES_MATRIX",
            "component": "HomeResourcesMatrix",
            "hardcoded_text_policy": "forbid",
            "required_tokens": [
                "LIT_RESOURCES_TITLE",
                "LIT_NAV_CASES",
                "LIT_NAV_LAWS",
                "LIT_NAV_COMPLIANCE"
            ]
        }
    ],
    "tokens": {
        "DISCL_READING_AID_ONLY": "This content is a Reading Aid Only and does not constitute legal advice.",
        "DISCL_NOT_COMPLIANCE": "Use of this tool does not guarantee compliance with any regulation.",
        "DISCL_NOT_CERTIFICATION": "This is a technical verification report, not a certification.",
        "DISCL_NO_ENDORSEMENT": "Validation results do not imply endorsement of the substrate.",
        "DISCL_NOT_SDK": "These artifacts are evidence contracts, not an SDK.",
        "LIT_NO_ENDORSEMENT": "No Endorsement",
        "LIT_STACK_FLOW": "Interop Stack Flow",
        "LIT_ROOT_CAUSE": "Root Cause Pointer",
        "LIT_REPLAY_INSTRUCTIONS": "Replay Instructions",
        "LIT_EVIDENCE_DOCKET": "Evidence Docket",
        "LIT_NOT_AVAILABLE": "Not Available",
        "LIT_NOT_APPLICABLE": "N/A",
        "DISCL_NOT_LEGAL_ADVICE": "Disclaimer: This evidence source is provided as-is data and does not constitute legal advice.",
        "LIT_DISPUTE_CLOSURE": "Dispute Closure",
        "LIT_CLAUSE_ID": "ID",
        "LIT_CLAUSE_NAME": "Clause Name",
        "LIT_INTENT": "Intent",
        "LIT_SURFACES": "Required Surfaces",
        "LIT_PRECEDENTS": "Precedents",
        "LIT_NO_CLAUSES": "No Clauses Found",
        "LIT_ARTICLE": "EU AI Act Article",
        "LIT_REQUIREMENT": "Requirement",
        "LIT_MPLP_CLAUSE": "MPLP Clause",
        "LIT_NO_MAPPINGS": "No Mappings Available",
        "LIT_RUN_ID": "Run ID",
        "LIT_RULESET_VERSION": "Ruleset Version",
        "LIT_SCHEMA_BUNDLE": "Schema Bundle",
        "LIT_PACK_ROOT_HASH": "Pack Root Hash",
        "LIT_ENV_REF": "Environment Ref",
        "LIT_PRODUCED_AT": "Produced At",
        "LIT_CHOOSE_ROLE": "Choose Your Role",
        "LIT_START_JOURNEY": "Start Journey",
        "LIT_LAWS_TITLE": "The Constitution",
        "LIT_LAWS_DESC": "GoldenFlow Ruleset & Compliance Standards",
        "LIT_RULESET_VERSION_LABEL": "Version",
        "LIT_FOOTER_RELEASE_LABEL": "RC-6 Sealed Release",
        "LIT_PROVENANCE_HEADER": "Execution Provenance",
        "LIT_PROTOCOL_REF": "Protocol Ref",
        "LIT_SUBSTRATE_REF": "Substrate Ref",
        "LIT_LAB_REF": "Lab Agent",
        "LIT_NAV_DOCKET": "The Docket",
        "LIT_NAV_START": "Start (Roles)",
        "LIT_NAV_CASES": "Cases",
        "LIT_NAV_LAWS": "The Constitution",
        "LIT_NAV_COMPLIANCE": "Compliance",
        "LIT_NAV_RULESETS": "Ruleset Diffpacks",
        "LIT_NAV_RELEASES": "Gate Reports",
        "LIT_HOME_TITLE": "Validation Lab",
        "LIT_HOME_SUBTITLE": "Evidence & Conformance Laboratory",
        "LIT_HOME_TAGLINE_NONCERT": "We verify evidence integrity and determinism — not runtime performance, not certification.",
        "LIT_CTA_CURATED_RUNS_TITLE": "Browse Curated Runs",
        "LIT_CTA_CURATED_RUNS_DESC": "Explore verified evidence packs from major frameworks.",
        "LIT_CTA_START_BY_ROLE_TITLE": "Start by Role",
        "LIT_CTA_START_BY_ROLE_DESC": "Tailored journeys for Architects, Auditors, and Compliance Officers.",
        "LIT_CTA_LOCAL_REPRO_TITLE": "How to Recheck Locally",
        "LIT_CTA_LOCAL_REPRO_DESC": "Download evidence packs and verify determinism on your machine.",
        "LIT_STATS_RUNS": "Curated Runs",
        "LIT_STATS_RULESET": "Active Ruleset",
        "LIT_STATS_DETERMINISM": "Determinism",
        "LIT_STATS_EVIDENCE_PACKS": "Evidence Packs",
        "LIT_AUDIT_BANNER_LINE1": "Non-Certification",
        "LIT_AUDIT_BANNER_LINE2": "Deterministic Adjudication",
        "LIT_AUDIT_BANNER_LINE3": "Pointer Closure",
        "LIT_QUICKSTART_TITLE": "Quick Start",
        "LIT_QUICKSTART_STEP1": "Install Dependencies",
        "LIT_QUICKSTART_STEP2": "Build Projections",
        "LIT_QUICKSTART_STEP3": "Run Gates",
        "LIT_RESOURCES_TITLE": "Protocol Resources",
        "LIT_REASON_PROJECTION_MISSING": "Projection Data Missing",
        "LIT_REASON_EVIDENCE_MISSING": "Evidence Slices Missing",
        "LIT_REASON_MAPPING_MISSING": "Mapping Not Provided",
        "LIT_ACTION_VIEW_EVIDENCE": "View Evidence Room",
        "LIT_ACTION_HOW_TO_REPRO": "How to Reproduce"
    }
};

// Flattened Tokens for Gate Validation
export const TOKENS: Record<string, string> = {
    "DISCL_READING_AID_ONLY": "This content is a Reading Aid Only and does not constitute legal advice.",
    "DISCL_NOT_COMPLIANCE": "Use of this tool does not guarantee compliance with any regulation.",
    "DISCL_NOT_CERTIFICATION": "This is a technical verification report, not a certification.",
    "DISCL_NO_ENDORSEMENT": "Validation results do not imply endorsement of the substrate.",
    "DISCL_NOT_SDK": "These artifacts are evidence contracts, not an SDK.",
    "LIT_NO_ENDORSEMENT": "No Endorsement",
    "LIT_STACK_FLOW": "Interop Stack Flow",
    "LIT_ROOT_CAUSE": "Root Cause Pointer",
    "LIT_REPLAY_INSTRUCTIONS": "Replay Instructions",
    "LIT_EVIDENCE_DOCKET": "Evidence Docket",
    "LIT_NOT_AVAILABLE": "Not Available",
    "LIT_NOT_APPLICABLE": "N/A",
    "DISCL_NOT_LEGAL_ADVICE": "Disclaimer: This evidence source is provided as-is data and does not constitute legal advice.",
    "LIT_DISPUTE_CLOSURE": "Dispute Closure",
    "LIT_CLAUSE_ID": "ID",
    "LIT_CLAUSE_NAME": "Clause Name",
    "LIT_INTENT": "Intent",
    "LIT_SURFACES": "Required Surfaces",
    "LIT_PRECEDENTS": "Precedents",
    "LIT_NO_CLAUSES": "No Clauses Found",
    "LIT_ARTICLE": "EU AI Act Article",
    "LIT_REQUIREMENT": "Requirement",
    "LIT_MPLP_CLAUSE": "MPLP Clause",
    "LIT_NO_MAPPINGS": "No Mappings Available",
    "LIT_RUN_ID": "Run ID",
    "LIT_RULESET_VERSION": "Ruleset Version",
    "LIT_SCHEMA_BUNDLE": "Schema Bundle",
    "LIT_PACK_ROOT_HASH": "Pack Root Hash",
    "LIT_ENV_REF": "Environment Ref",
    "LIT_PRODUCED_AT": "Produced At",
    "LIT_CHOOSE_ROLE": "Choose Your Role",
    "LIT_START_JOURNEY": "Start Journey",
    "LIT_LAWS_TITLE": "The Constitution",
    "LIT_LAWS_DESC": "GoldenFlow Ruleset & Compliance Standards",
    "LIT_RULESET_VERSION_LABEL": "Version",
    "LIT_FOOTER_RELEASE_LABEL": "RC-6 Sealed Release",
    "LIT_PROVENANCE_HEADER": "Execution Provenance",
    "LIT_PROTOCOL_REF": "Protocol Ref",
    "LIT_SUBSTRATE_REF": "Substrate Ref",
    "LIT_LAB_REF": "Lab Agent",
    "LIT_NAV_DOCKET": "The Docket",
    "LIT_NAV_START": "Start (Roles)",
    "LIT_NAV_CASES": "Cases",
    "LIT_NAV_LAWS": "The Constitution",
    "LIT_NAV_COMPLIANCE": "Compliance",
    "LIT_NAV_RULESETS": "Ruleset Diffpacks",
    "LIT_NAV_RELEASES": "Gate Reports",
    "LIT_HOME_TITLE": "Validation Lab",
    "LIT_HOME_SUBTITLE": "Evidence & Conformance Laboratory",
    "LIT_HOME_TAGLINE_NONCERT": "We verify evidence integrity and determinism — not runtime performance, not certification.",
    "LIT_CTA_CURATED_RUNS_TITLE": "Browse Curated Runs",
    "LIT_CTA_CURATED_RUNS_DESC": "Explore verified evidence packs from major frameworks.",
    "LIT_CTA_START_BY_ROLE_TITLE": "Start by Role",
    "LIT_CTA_START_BY_ROLE_DESC": "Tailored journeys for Architects, Auditors, and Compliance Officers.",
    "LIT_CTA_LOCAL_REPRO_TITLE": "How to Recheck Locally",
    "LIT_CTA_LOCAL_REPRO_DESC": "Download evidence packs and verify determinism on your machine.",
    "LIT_STATS_RUNS": "Curated Runs",
    "LIT_STATS_RULESET": "Active Ruleset",
    "LIT_STATS_DETERMINISM": "Determinism",
    "LIT_STATS_EVIDENCE_PACKS": "Evidence Packs",
    "LIT_AUDIT_BANNER_LINE1": "Non-Certification",
    "LIT_AUDIT_BANNER_LINE2": "Deterministic Adjudication",
    "LIT_AUDIT_BANNER_LINE3": "Pointer Closure",
    "LIT_QUICKSTART_TITLE": "Quick Start",
    "LIT_QUICKSTART_STEP1": "Install Dependencies",
    "LIT_QUICKSTART_STEP2": "Build Projections",
    "LIT_QUICKSTART_STEP3": "Run Gates",
    "LIT_RESOURCES_TITLE": "Protocol Resources",
    "LIT_REASON_PROJECTION_MISSING": "Projection Data Missing",
    "LIT_REASON_EVIDENCE_MISSING": "Evidence Slices Missing",
    "LIT_REASON_MAPPING_MISSING": "Mapping Not Provided",
    "LIT_ACTION_VIEW_EVIDENCE": "View Evidence Room",
    "LIT_ACTION_HOW_TO_REPRO": "How to Reproduce"
};

export const PAGE_BINDINGS = [
    {
        "id": "home",
        "route": "/",
        "context_type": "ssot",
        "blocks": [
            "BLOCK_HOME_HERO",
            "BLOCK_HOME_PRIMARY_CTAS",
            "BLOCK_HOME_STATS_ROW",
            "BLOCK_HOME_AUDIT_BANNER",
            "BLOCK_HOME_QUICK_START",
            "BLOCK_HOME_RESOURCES_MATRIX"
        ]
    },
    {
        "id": "start",
        "route": "/start",
        "blocks": [
            "BLOCK_START_HERO",
            "BLOCK_ROLE_GATEWAY"
        ]
    },
    {
        "id": "case_detail",
        "route": "/cases/[id]",
        "context_type": "projection",
        "blocks": [
            "BLOCK_VERDICT_BADGE",
            "BLOCK_PROVENANCE",
            "BLOCK_INTEROP_VISUALIZER",
            "BLOCK_DISPUTE_PANEL"
        ]
    },
    {
        "id": "evidence_room",
        "route": "/cases/[id]/evidence",
        "context_type": "projection",
        "blocks": [
            "BLOCK_EVIDENCE_DOCKET",
            "BLOCK_MANIFEST_VIEWER"
        ]
    },
    {
        "id": "reg_mapping",
        "route": "/policies/reg-mapping",
        "context_type": "ruleset",
        "blocks": [
            "BLOCK_REG_MAPPING_MATRIX",
            "BLOCK_DISCLAIMER_BANNER"
        ]
    },
    {
        "id": "laws",
        "route": "/laws",
        "context_type": "ruleset",
        "blocks": [
            "BLOCK_HERO",
            "BLOCK_CLAUSE_BROWSER"
        ]
    }
];
